plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest


env:
  es6: true
  node: true

extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules: {
  "no-console": "off", 
  "import/extensions": "off",
  "no-underscore-dangle": [2, { "allow": ["__filename", "__dirname"] }],
}